# ~/.config/starship.toml

[username]
style_user = "yellow"
style_root = "black bold"
format = " [@$user]($style) on"
disabled = false
show_always = true

[hostname]
ssh_only = false
format =  " [$hostname](bold blue) "
trim_at = "."
disabled = false

[shell]
powershell_indicator = "[ï‘ pwsh](blue)"
bash_indicator = "[ï‘ bash](yellow)"
unknown_indicator = "mystery shell"
disabled = false

[shlvl]
disabled = false
format = "[$symbol$shlvl]($style) "
threshold = 2

[character]
success_symbol = "[ğŸ‘>](green) "
error_symbol = "[ğŸ‘>](red) "


[directory]
read_only = " ï€£ "
truncation_symbol = " ../"
truncation_length = 5
repo_root_style = "bold white"
repo_root_format = "[$before_root_path]($style)[$repo_root ï„“ ]($repo_root_style)[$path]($style)[$read_only]($read_only_style) " 

[time]
disabled = false
format = '[\[ $time \]]($style) '
time_format = "%T"
utc_time_offset = "-3"

[cmd_duration]
min_time = 1_000
show_milliseconds = true

[aws]
symbol = "îŒ½ "

[battery]
full_symbol = "ï•¸"
charging_symbol = "ï–ƒ"
discharging_symbol = "ï–‚"

[conda]
ignore_base = true
symbol = "ï„Œ "
format = "[$symbol$environment](dimmed green) "

[docker_context]
symbol = "ïŒˆ "

[dotnet]
symbol = "î¿ "
format = "[$symbol$version( ï§½ $tfm)]($style) "

[elixir]
symbol = "î‰µ "

[elm]
symbol = "î˜¬ "

[git_branch]
symbol = "ï˜ "
style = "bold purple"
format ="-- [$symbol$branch ]($style)"

[git_commit]
disabled = false

[golang]
symbol = "î˜§ "

[hg_branch]
symbol = "ï˜ "

[java]
symbol = "î‰– "

	[julia]
symbol = "î˜¤ "

[memory_usage]
symbol = "ï¡š "

[nim]
symbol = "ïš¤ "

[nix_shell]
symbol = "ï‹œ "

[nodejs]
symbol = "î‰ "

[package]
symbol = "ï£– "

[php]
symbol = "î˜ˆ "

[python]
symbol = "î˜† "
python_binary = "python3"

[ruby]
symbol = "îˆ¾ "

[rust]
symbol = "ï€“ "

[rlang]
symbol = "R "
